[build]
  command = "npm run export:web"
  publish = "dist-test"

[[headers]]
  for = "/manuals/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/_expo/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
