#!/usr/bin/env python3
import json
import re
import ssl
import sys
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
VENDOR = ROOT / "tools" / "vendor"
sys.path.insert(0, str(VENDOR))

from pypdf import PdfReader

BASE_URL = "https://www.hosp.med.osaka-u.ac.jp/home/hp-infect/file/manual"
PDF_DIR = ROOT / "source-pdfs"
OUTPUT = ROOT / "src" / "data" / "manualContents.js"

PDFS = [
    "1.pdf",
    "2-1.pdf",
    "2-2.pdf",
    "3-1.pdf",
    "4.pdf",
    "5-1.pdf",
    "5-2ingai.pdf",
    "5-3ingai.pdf",
    "5-4ingai.pdf",
    "5-5ingai.pdf",
    "5-6ingai.pdf",
    "5-7ingai.pdf",
    "5-8ingai.pdf",
    "5-9ingai.pdf",
    "5-10ingai.pdf",
    "5-11ingai.pdf",
    "5-12ingai.pdf",
    "5-13ingai.pdf",
    "5-14ingai.pdf",
    "6-1.pdf",
    "6-2.pdf",
    "6-3.pdf",
    "6-4.pdf",
    "7-1.pdf",
    "7-2.pdf",
    "8ingai.pdf",
    "10.pdf",
    "11.pdf",
    "kaitei.pdf",
]


def content_id(filename):
    return filename.removesuffix(".pdf")


def download(filename):
    PDF_DIR.mkdir(parents=True, exist_ok=True)
    target = PDF_DIR / filename
    if target.exists() and target.stat().st_size > 0:
        return target

    url = f"{BASE_URL}/{filename}"
    print(f"download {url}")
    context = ssl._create_unverified_context()
    with urllib.request.urlopen(url, timeout=30, context=context) as response:
        target.write_bytes(response.read())
    return target


def clean_text(text):
    text = text.replace("\r\n", "\n").replace("\r", "\n")
    text = text.translate(str.maketrans({
        "\uf06c": "・",
        "\uf09e": "・",
        "\uf0d8": "・",
        "\uf0fc": "・",
        "\uf0b2": "・",
    }))
    text = re.sub(r"[ \t\u3000]+", " ", text)
    text = re.sub(r"\n{3,}", "\n\n", text)
    return text.strip()


def paragraphs(text):
    blocks = []
    for block in re.split(r"\n\s*\n", text):
        lines = [line.strip() for line in block.splitlines() if line.strip()]
        if not lines:
            continue
        blocks.append("\n".join(lines))
    return blocks


def extract(path):
    reader = PdfReader(str(path))
    page_texts = []
    for index, page in enumerate(reader.pages, start=1):
        text = clean_text(page.extract_text() or "")
        page_texts.append({
            "page": index,
            "paragraphs": paragraphs(text),
            "text": text,
        })

    full_text = clean_text("\n\n".join(page["text"] for page in page_texts))
    return {
        "id": content_id(path.name),
        "filename": path.name,
        "url": f"{BASE_URL}/{path.name}",
        "pageCount": len(reader.pages),
        "pages": page_texts,
        "searchText": full_text,
    }


def write_js(contents):
    payload = json.dumps(contents, ensure_ascii=False, indent=2)
    OUTPUT.write_text(
        "// Generated by tools/extract_manual_text.py\n"
        "// Do not edit this file by hand. Update the official PDFs and regenerate instead.\n"
        f"export const manualContents = {payload};\n",
        encoding="utf-8",
    )


def main():
    contents = {}
    for filename in PDFS:
        path = download(filename)
        contents[content_id(filename)] = extract(path)
        print(f"extracted {filename}")
    write_js(contents)
    print(f"wrote {OUTPUT}")


if __name__ == "__main__":
    main()
